name: Auto commit

on:
  push:
    branches:
      - master
      - main

  schedule:
    - cron: "28 * * * *"

  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: auto-commit-${{ github.ref }}
  cancel-in-progress: false

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: DEBUG
        run: echo "::debug::Ref = ${{github.ref}}"

      - uses: actions/checkout@v5
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED

      - name: Commit changes
        run: |
          git config --local user.email "asrofilnadibs28@gmail.com"
          git config --local user.name "asrofilnadib"

          arr[0]="chore(bot): 😂 auto commit"
          arr[1]="chore(bot): 😱 auto commit"
          arr[2]="chore(bot): 👿 auto commit"
          arr[3]="chore(bot): 🤖 auto commit"
          arr[4]="chore(bot): 🟩 auto commit"

          for i in 1 2 3 4 5; do
            d=$(date -u '+%Y-%m-%dT%H:%M:%S')Z
            echo "${d}" > LAST_UPDATED
            git add LAST_UPDATED
            rand=$((RANDOM % ${#arr[@]}))
            git diff --staged --quiet || git commit -m "${arr[$rand]}"
            sleep 1
          done

      - name: GitHub Push
        run: |
          git pull --rebase origin "$GITHUB_REF_NAME"
          git push origin "HEAD:$GITHUB_REF_NAME"
